# Importing libraries

In [1]:
import numpy as np
import pandas as pd

# Loading DATA SET

In [2]:
ds=pd.read_csv(r"C:\Users\user\Desktop\DataSets\social_network_ads.csv")

In [3]:
ds

User ID  Gender  Age  EstimatedSalary  Purchased
0    15624510    Male   19            19000          0
1    15810944    Male   35            20000          0
2    15668575  Female   26            43000          0
3    15603246  Female   27            57000          0
4    15804002    Male   19            76000          0
..        ...     ...  ...              ...        ...
395  15691863  Female   46            41000          1
396  15706071    Male   51            23000          1
397  15654296  Female   50            20000          1
398  15755018    Male   36            33000          0
399  15594041  Female   49            36000          1

[400 rows x 5 columns]

In [4]:
ds.head()

User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510    Male   19            19000          0
1  15810944    Male   35            20000          0
2  15668575  Female   26            43000          0
3  15603246  Female   27            57000          0
4  15804002    Male   19            76000          0

In [5]:
ds.tail()

User ID  Gender  Age  EstimatedSalary  Purchased
395  15691863  Female   46            41000          1
396  15706071    Male   51            23000          1
397  15654296  Female   50            20000          1
398  15755018    Male   36            33000          0
399  15594041  Female   49            36000          1

In [6]:
ds.dtypes

User ID             int64
Gender             object
Age                 int64
EstimatedSalary     int64
Purchased           int64
dtype: object

In [7]:
ds.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype 
---  ------           --------------  ----- 
 0   User ID          400 non-null    int64 
 1   Gender           400 non-null    object
 2   Age              400 non-null    int64 
 3   EstimatedSalary  400 non-null    int64 
 4   Purchased        400 non-null    int64 
dtypes: int64(4), object(1)
memory usage: 15.8+ KB


In [8]:
ds.describe()

User ID         Age  EstimatedSalary   Purchased
count  4.000000e+02  400.000000       400.000000  400.000000
mean   1.569154e+07   37.655000     69742.500000    0.357500
std    7.165832e+04   10.482877     34096.960282    0.479864
min    1.556669e+07   18.000000     15000.000000    0.000000
25%    1.562676e+07   29.750000     43000.000000    0.000000
50%    1.569434e+07   37.000000     70000.000000    0.000000
75%    1.575036e+07   46.000000     88000.000000    1.000000
max    1.581524e+07   60.000000    150000.000000    1.000000

In [9]:
ds.Age.unique()

array([19, 35, 26, 27, 32, 25, 20, 18, 29, 47, 45, 46, 48, 49, 31, 21, 28,
       33, 30, 23, 24, 22, 59, 34, 39, 38, 37, 42, 40, 36, 41, 58, 55, 52,
       60, 56, 53, 50, 51, 57, 44, 43, 54], dtype=int64)

In [10]:
ds.Age.nunique()

43

# Identify null values

In [11]:
ds.isnull().sum()

User ID            0
Gender             0
Age                0
EstimatedSalary    0
Purchased          0
dtype: int64

In [12]:
ds

User ID  Gender  Age  EstimatedSalary  Purchased
0    15624510    Male   19            19000          0
1    15810944    Male   35            20000          0
2    15668575  Female   26            43000          0
3    15603246  Female   27            57000          0
4    15804002    Male   19            76000          0
..        ...     ...  ...              ...        ...
395  15691863  Female   46            41000          1
396  15706071    Male   51            23000          1
397  15654296  Female   50            20000          1
398  15755018    Male   36            33000          0
399  15594041  Female   49            36000          1

[400 rows x 5 columns]

# Drop user ID

In [13]:
ds1=ds.drop(['User ID'],axis=1)

In [14]:
ds1

Gender  Age  EstimatedSalary  Purchased
0      Male   19            19000          0
1      Male   35            20000          0
2    Female   26            43000          0
3    Female   27            57000          0
4      Male   19            76000          0
..      ...  ...              ...        ...
395  Female   46            41000          1
396    Male   51            23000          1
397  Female   50            20000          1
398    Male   36            33000          0
399  Female   49            36000          1

[400 rows x 4 columns]

In [15]:
ds1.columns

Index(['Gender', 'Age', 'EstimatedSalary', 'Purchased'], dtype='object')

# DEPENDENT VARIABLES

In [16]:
x=ds1[['Gender', 'Age', 'EstimatedSalary']].values

In [17]:
x

array([['Male', 19, 19000],
       ['Male', 35, 20000],
       ['Female', 26, 43000],
       ...,
       ['Female', 50, 20000],
       ['Male', 36, 33000],
       ['Female', 49, 36000]], dtype=object)

# INDEPENDENT VARIABLES

In [18]:
y=ds1[['Purchased']].values

In [59]:
y[:5]

array([[0],
       [0],
       [0],
       [0],
       [0]], dtype=int64)

In [61]:
y[:5]

array([[0],
       [0],
       [0],
       [0],
       [0]], dtype=int64)

In [21]:
y.shape

(400, 1)

# LABEL ENCODING

In [22]:
from sklearn.preprocessing import LabelEncoder

In [23]:
label=LabelEncoder()
x[:,0]=label.fit_transform(x[:,0])

In [24]:
x

array([[1, 19, 19000],
       [1, 35, 20000],
       [0, 26, 43000],
       ...,
       [0, 50, 20000],
       [1, 36, 33000],
       [0, 49, 36000]], dtype=object)

In [25]:
from sklearn.model_selection import train_test_split

In [26]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2)

In [27]:
x_train.shape

(320, 3)

In [28]:
x.shape

(400, 3)

In [29]:
x_test.shape

(80, 3)

In [30]:
y_train.shape

(320, 1)

In [31]:
y_test.shape

(80, 1)

# STANDARD SCALER

In [32]:
from sklearn.preprocessing import StandardScaler

In [33]:
sc=StandardScaler()

In [34]:
x_train=sc.fit_transform(x_train)

In [58]:
x_train[:5]

array([[1.        , 0.11904762, 0.35555556],
       [1.        , 0.28571429, 0.88888889],
       [0.        , 0.19047619, 0.        ],
       [0.        , 0.33333333, 1.        ],
       [1.        , 0.4047619 , 0.56296296]])

In [36]:
y_train=sc.fit_transform(y_train)

In [37]:
y_train

array([[-0.74390729],
       [ 1.34425353],
       [-0.74390729],
       [ 1.34425353],
       [ 1.34425353],
       [-0.74390729],
       [-0.74390729],
       [ 1.34425353],
       [ 1.34425353],
       [-0.74390729],
       [-0.74390729],
       [ 1.34425353],
       [ 1.34425353],
       [ 1.34425353],
       [-0.74390729],
       [ 1.34425353],
       [ 1.34425353],
       [ 1.34425353],
       [ 1.34425353],
       [-0.74390729],
       [ 1.34425353],
       [-0.74390729],
       [-0.74390729],
       [-0.74390729],
       [-0.74390729],
       [ 1.34425353],
       [ 1.34425353],
       [ 1.34425353],
       [-0.74390729],
       [-0.74390729],
       [-0.74390729],
       [-0.74390729],
       [ 1.34425353],
       [-0.74390729],
       [ 1.34425353],
       [ 1.34425353],
       [ 1.34425353],
       [-0.74390729],
       [ 1.34425353],
       [ 1.34425353],
       [-0.74390729],
       [ 1.34425353],
       [ 1.34425353],
       [-0.74390729],
       [ 1.34425353],
       [ 1

In [38]:
x_test=sc.fit_transform(x_test)

In [57]:
x_test[:5]

array([[0.        , 0.04878049, 0.50757576],
       [0.        , 0.43902439, 0.29545455],
       [0.        , 0.41463415, 1.        ],
       [0.        , 0.12195122, 0.50757576],
       [1.        , 0.31707317, 0.46212121]])

In [40]:
y_test=sc.fit_transform(y_test)

In [56]:
y_test[:5]

array([[0.],
       [0.],
       [1.],
       [0.],
       [0.]])

In [42]:
y_test.size

80

# MINMAX SCALAR

In [43]:
from sklearn.preprocessing import MinMaxScaler

In [55]:
min_max=MinMaxScaler()
x_train=min_max.fit_transform(x_train)
x_train[:5]

array([[1.        , 0.11904762, 0.35555556],
       [1.        , 0.28571429, 0.88888889],
       [0.        , 0.19047619, 0.        ],
       [0.        , 0.33333333, 1.        ],
       [1.        , 0.4047619 , 0.56296296]])

In [54]:
y_train=min_max.fit_transform(y_train)
y_train[:5]

array([[0.],
       [1.],
       [0.],
       [1.],
       [1.]])

In [53]:
x_test=min_max.fit_transform(x_test)
x_test[:5]

array([[0.        , 0.04878049, 0.50757576],
       [0.        , 0.43902439, 0.29545455],
       [0.        , 0.41463415, 1.        ],
       [0.        , 0.12195122, 0.50757576],
       [1.        , 0.31707317, 0.46212121]])

In [52]:
y_test=min_max.fit_transform(y_test)
y_test[:5]

array([[0.],
       [0.],
       [1.],
       [0.],
       [0.]])