In [1]:
import numpy as np
import pandas as pd

In [2]:
ds=pd.read_csv(r"C:\Users\user\Desktop\DataSets\Datapre.csv")

In [3]:
ds

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany   NaN  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0  45000.0       Yes
5   France  35.0      NaN       Yes
6    Spain  40.0  52000.0        No
7   France  48.0  79000.0       NaN
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

In [4]:
ds.head(5)

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany   NaN  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0  45000.0       Yes

In [5]:
ds.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   Country    10 non-null     object 
 1   Age        9 non-null      float64
 2   Salary     9 non-null      float64
 3   Purchased  9 non-null      object 
dtypes: float64(2), object(2)
memory usage: 448.0+ bytes


In [6]:
ds.describe()

Age        Salary
count   9.000000      9.000000
mean   39.888889  62333.333333
std     6.954215  13711.309201
min    27.000000  45000.000000
25%    37.000000  52000.000000
50%    40.000000  61000.000000
75%    44.000000  72000.000000
max    50.000000  83000.000000

In [7]:
ds.dtypes

Country       object
Age          float64
Salary       float64
Purchased     object
dtype: object

In [8]:
ds.Salary.values

array([72000., 48000., 54000., 61000., 45000.,    nan, 52000., 79000.,
       83000., 67000.])

In [9]:
ds.Salary.unique()

array([72000., 48000., 54000., 61000., 45000.,    nan, 52000., 79000.,
       83000., 67000.])

In [10]:
ds.Salary.nunique()

9

In [11]:
ds['Salary'].unique()

array([72000., 48000., 54000., 61000., 45000.,    nan, 52000., 79000.,
       83000., 67000.])

In [12]:
ds.isnull().sum()

Country      0
Age          1
Salary       1
Purchased    1
dtype: int64

In [13]:
ds.columns


Index(['Country', 'Age', 'Salary', 'Purchased'], dtype='object')

In [14]:
ds

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany   NaN  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0  45000.0       Yes
5   France  35.0      NaN       Yes
6    Spain  40.0  52000.0        No
7   France  48.0  79000.0       NaN
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

In [15]:
x=ds[['Country', 'Age', 'Salary']].values

In [16]:
x

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', nan, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, 45000.0],
       ['France', 35.0, nan],
       ['Spain', 40.0, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

In [17]:
y=ds[['Purchased']].values

In [18]:
!pip install scikit-learn

In [19]:
from sklearn.impute import SimpleImputer

In [20]:
imputer=SimpleImputer(missing_values=np.nan,strategy='mean')
x[:,1:3]=imputer.fit_transform(x[:,1:3])

In [21]:
x

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 39.888888888888886, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, 45000.0],
       ['France', 35.0, 62333.333333333336],
       ['Spain', 40.0, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

In [22]:
imputer1=SimpleImputer(missing_values=np.nan,strategy='most_frequent')   
y=imputer1.fit_transform(y)
y

array([['No'],
       ['Yes'],
       ['No'],
       ['No'],
       ['Yes'],
       ['Yes'],
       ['No'],
       ['No'],
       ['No'],
       ['Yes']], dtype=object)

In [23]:
from sklearn.preprocessing import LabelEncoder

In [24]:
label=LabelEncoder()

In [25]:
x[:,0]=label.fit_transform(x[:,0])

In [26]:
x

array([[0, 44.0, 72000.0],
       [2, 27.0, 48000.0],
       [1, 39.888888888888886, 54000.0],
       [2, 38.0, 61000.0],
       [1, 40.0, 45000.0],
       [0, 35.0, 62333.333333333336],
       [2, 40.0, 52000.0],
       [0, 48.0, 79000.0],
       [1, 50.0, 83000.0],
       [0, 37.0, 67000.0]], dtype=object)

In [27]:
label1=LabelEncoder()
y=label1.fit_transform(y)

C:\Users\user\anaconda3\lib\site-packages\sklearn\preprocessing\_label.py:115: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [28]:
y

array([0, 1, 0, 0, 1, 1, 0, 0, 0, 1])

In [29]:
from sklearn.model_selection import train_test_split

In [30]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2)

In [31]:
x_train.shape

(8, 3)

In [32]:
x.shape

(10, 3)

In [33]:
y_train.shape

(8,)

In [34]:
x_test.shape

(2, 3)

In [35]:
y_test.shape

(2,)

In [36]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_train=sc.fit_transform(x_train)

In [37]:
x_train

array([[ 0.        ,  0.17459169, -1.28332043],
       [ 1.15470054, -0.16980836,  0.16607676],
       [-1.15470054,  0.8633918 ,  1.16253733],
       [ 1.15470054,  0.17459169, -0.64920916],
       [ 0.        ,  0.15545836, -0.46803451],
       [-1.15470054, -0.68640844,  0.28685986],
       [ 1.15470054, -2.06400864, -1.01155846],
       [-1.15470054,  1.5521919 ,  1.7966486 ]])

In [38]:
x_test=sc.fit_transform(x_test)

In [39]:
x_test

array([[-1., -1., -1.],
       [ 1.,  1.,  1.]])